"""Evo 設定模組封裝。"""

from config.settings import (
    AI_EVOLUTION_COOLDOWN,
    BACKUPS_DIR,
    DB_PATH,
    HABITAT_DIR,
    HISTORY_DIR,
    MAX_CPU_PERCENT,
    MAX_HABITAT_SIZE_BYTES,
    MAX_RAM_BYTES,
    MAX_SUBPROCESSES,
    OBSERVER_DIR,
    PROJECT_ROOT,
    PROMPTS_DIR,
    RUNTIME_DIR,
    SKILLS_DIR,
    TICK_SPEEDS,
    EvoConfig,
    config,
)

__all__ = [
    "PROJECT_ROOT",
    "RUNTIME_DIR",
    "HABITAT_DIR",
    "BACKUPS_DIR",
    "HISTORY_DIR",
    "SKILLS_DIR",
    "PROMPTS_DIR",
    "OBSERVER_DIR",
    "DB_PATH",
    "TICK_SPEEDS",
    "AI_EVOLUTION_COOLDOWN",
    "MAX_CPU_PERCENT",
    "MAX_RAM_BYTES",
    "MAX_SUBPROCESSES",
    "MAX_HABITAT_SIZE_BYTES",
    "EvoConfig",
    "config",
]
